- name: istall mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start and enable mysql service
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: set root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
