- name: istall mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start and enable mysql service
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: install boto3 and botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - boto3
  - botocore

- name: set root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{ MYSQL_ROOT_PASSWORD }}
