- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs

- name: copy mongo repo file to /etc/yum.repos.d/mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb-mongosh client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: check if the master data is loaded or not into the mongo server
  ansible.builtin.command: mongosh --host mongodb.nanda.cyou --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: load_check

- name: check the data is loaded or not
  ansible.builtin.debug:
    msg: "{{ load_check }}"

- name: load products
  ansible.builtin.shell: mongosh --host mongodb.nanda.cyou < /app/db/master-data.js
  when: load_check.stdout | int < 0

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd.yaml

# - name: deployment
#   tags:
#   - deployment
#   import_role:
#     name: common
#     tasks_from: deployment