- name: install python 3
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - python3
  - gcc
  - python3-devel

- name: download dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
  args:
    chdir: /app